export const LOAD_INPUT_DATA = 'LOAD_INPUT_DATA';

export const RESET_INPUT_FORM = 'RESET_INPUT_FORM';
export const EDIT_INPUT_FORM = 'EDIT_INPUT_FORM';

export const RESET_NODE_FORM = 'RESET_NODE_FORM';
export const EDIT_NODE_FORM = 'EDIT_NODE_FORM';

export const SWAP_TREE = 'SWAP_TREE';
export const SWAP_NODE_AT_PATH = 'SWAP_NODE_AT_PATH';
export const REMOVE_NODE_AT_PATH = 'REMOVE_NODE_AT_PATH';
export const ADD_NEW_NODE = 'ADD_NEW_NODE';
